### ISSUE TITLE
主题存在的问题

### ISSUE THREAD

**Issue by kookob** [tangkunyin/hexo-theme-jsimple#1]
该主题看起来很不错，但是有两个地方实在不舒服。
1、就是右边的滚动条，没办法用鼠标去拖动，鼠标一移到右边，就弹出目录，把鼠标遮挡了。
2、左边分类之后的文章，点一下，目录又回到所有文章了。

**Comment by tangkunyin** [comment]
多谢楼上盆友反馈。我抽时间改改

**Comment by tangkunyin** [comment]
第二个问题应该没事了
