### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by quanoc** [tangkunyin/hexo-theme-jsimple#10]
如果文章的 categories: ... 没有设置，主题就会报错。
/opt/myGithub/blog-nova/themes/jsimple/layout/_partial/_post.ejs:5
page.categories.first().name

**Comment by tangkunyin** [comment]
@damoncs 这是个必选项，因为菜单是通过那个读出来的

**Comment by quanoc** [comment]
ok。觉得这个主题很棒！我可以用这个主题吗？有没有什么版权问题呀！我对这块不太懂。

**Comment by tangkunyin** [comment]
@damoncs 可以用，免费开源的。你随意，高兴就行 ：）
