### ISSUE TITLE
post信息填写变复杂了

### ISSUE THREAD

**Issue by mzeht** [tangkunyin/hexo-theme-jsimple#12]
之前在主题下配置好avatar: /images/favicon.png，authorDesc，author ,页面就有了，现在post里面没有定义的画 图片显示不了 字段显示undefined

**Comment by tangkunyin** [comment]
@mzeht 在模板文件里设置一下，如果就你一人写作的话，这是一劳永逸的做法。不需要每次在post文件里写的

**Comment by mzeht** [comment]
@tangkunyin  模版文件改了 但是以前很多旧文件还是要手动修改

**Comment by tangkunyin** [comment]
@mzeht 好吧，这真不是个好消息。目前只能人肉改了....有精力的话可以写个脚本
