### ISSUE TITLE
搜索功能需要特殊的配置吗？我的搜索功能不可用

### ISSUE THREAD

**Issue by aStudyer** [tangkunyin/hexo-theme-jsimple#14]

**Comment by tangkunyin** [comment]
```
"dependencies": {
    "hexo": "^3.2.2",
    "hexo-git-backup": "^0.1.2",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.11",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-deployer-git": "0.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-generator-json-content": "^2.2.0"
  }
```
@aStudyer 看看你的hexo依赖都对么，稍后有时间我更新下文档，我可能没说清楚，不好意思

**Comment by aStudyer** [comment]
依赖必须都一样吗？@tangkunyin

**Comment by tangkunyin** [comment]
@aStudyer 如果要使用这个主题，就必须有这些依赖啊

**Comment by aStudyer** [comment]
@tangkunyin 这些依赖我都有，但是部分版本不太一样。现在所有的功能都没问题，就是点击搜索框没有所有文章的下拉列表，我看了半天，也没看到你是在哪里配置的，好像并没有单独配置搜索界面的地方。都是模板配好的吧？

**Comment by aStudyer** [comment]
还有404界面结束之后，总是跳到说IT网站，怎么修改啊？

**Comment by tangkunyin** [comment]
@aStudyer 搜索无需配置，安装依赖后，执行`hexo g`后，在`public`文件加中会有`content.json`文件，这里是搜索的数据，搜索就是总这里读的数据。在不懂，看我网站备份。文档里有说明，好好看看。
另，404是个静态的HTML，你改下跳转链接就好！

**Comment by aStudyer** [comment]
还有一个问题，每次我deploy之后，相应的CNAME文件就丢失了，每次deploy都需要重新创建CNAME文件，这个怎么解决啊？

**Comment by tangkunyin** [comment]
@aStudyer 请更新最新主题，或者把CNAME文件放到主题的`source`文件夹中，这样就不会丢了
