### ISSUE TITLE
tags page not found

### ISSUE THREAD

**Issue by jimmyrengga** [tangkunyin/hexo-theme-jsimple#16]
hi @tangkunyin, i cannot generate tags page since i clone your themes repository, any solutions?

**Comment by tangkunyin** [comment]
hi, it looks you have not config your tags and archive in site config yml file.
you may look this document first:https://github.com/tangkunyin/hexo-theme-jsimple/blob/master/README.md

also read my site backup:  https://github.com/shuoit/blog
