### ISSUE TITLE
请教[影藏侧边栏效果怎么实现的]

### ISSUE THREAD

**Issue by wuchangfeng** [tangkunyin/hexo-theme-jsimple#2]
您好，对前段这块不是太懂，想请教一下，点一下右上角的那个按钮，左边布局影藏，这块代码具体在哪一部分？或者怎么实现的？谢谢

**Comment by tangkunyin** [comment]
这个是在js里控制的，你可以研究下

**Comment by manwuyu** [comment]
js-lib.js 里面

// Enable fullscreen.
$('#js-fullscreen').on('click', function() {
    if (button.hasClass('fullscreen')) {
        sidebar.removeClass('fullscreen');
        button.removeClass('fullscreen');
        content.delay(300).queue(function(){
            $(this).removeClass('fullscreen').dequeue();
        });
    } else {
        sidebar.addClass('fullscreen');
        button.addClass('fullscreen');
        content.delay(200).queue(function(){
            $(this).addClass('fullscreen').dequeue();
        });
    }
});

**Comment by tangkunyin** [comment]
楼上说的很好
