### ISSUE TITLE
模板问题

### ISSUE THREAD

**Issue by Esusi** [tangkunyin/hexo-theme-jsimple#23]
hi  tangkunyin，
     我使用你的模板，做完readme操作后，遇到些问题，问问看，能不能解决！

![03](https://user-images.githubusercontent.com/4463220/30633159-39621eec-9e1d-11e7-9063-c7bc373446fd.png)

![01](https://user-images.githubusercontent.com/4463220/30633032-cba97bc0-9e1c-11e7-9594-a161772a5fab.png)
![04](https://user-images.githubusercontent.com/4463220/30633211-7145f77a-9e1d-11e7-821c-bf9c43d9d095.png)

**Comment by tangkunyin** [comment]
<img width="1300" alt="1" src="https://user-images.githubusercontent.com/4197468/30677853-fd69bef4-9e53-11e7-9d80-bb54742d7e2a.png">
<img width="829" alt="2" src="https://user-images.githubusercontent.com/4197468/30677862-09164790-9e54-11e7-82a0-de22797483df.png">

注意多看主题使用说明，我写了篇文章，还有我的站点备份，都有详情配置，看源码也能找到的
