### ISSUE TITLE
为博客文章添加目录时出现问题

### ISSUE THREAD

**Issue by FinZhang** [tangkunyin/hexo-theme-jsimple#24]
谢谢您开发的博客主题！今天我在给博客文章添加目录的时候遇到了两个问题，不知道是不是我哪里操作有误。
1.我在`/themes/jsimple/layout/_widget`的`common-article.ejs`里添加了关于目录的代码
`

	
	<% if (!index && post.toc){ %>
	<div id="toc" class="toc-article">
	<strong class="toc-title">文章目录</strong>
	<%- toc(post.content, {list_number: false}) %>
	</div>
	<% } %>  
 `
目录能够正常显示，但是会有一个异常编号出现在目录超链接前，如图

![](http://wx3.sinaimg.cn/mw690/005Xteq2gy1fmmh5km566j304b06f747.jpg)

我已经关掉了toc默认的标号，但是这个没有包含在超链接里的编号不知道是怎么来的，网上也没有找到解决方案。

2.第二个问题是我尝试修改这个目录的样式，我看大多数教程都是在` /themes/jsimple/source/css/_partial `下新建和修改styl文件，担这个主题并不是这么写CSS的，我尝试把教程里的styl文件内容放到insight.styl和SimpleStyle.css两个文件里，都没有效果，请问我应该怎么做才能自定义目录样式？

**Comment by tangkunyin** [comment]
@FinZhang 这是上个版本的主题。我已经不维护了，你可以试试当前这个版本，比那个棒多了，希望你会喜欢

**Comment by tangkunyin** [comment]
@FinZhang  这是上个版本的主题。我已经不维护了，你可以试试当前这个版本，比那个棒多了，希望你会喜欢
