### ISSUE TITLE
分类文章过滤问题

### ISSUE THREAD

**Issue by ghost** [tangkunyin/hexo-theme-jsimple#26]
分类这块比如前端，后台，设计等这块怎么处理过滤文章的

**Comment by tangkunyin** [comment]
@ruizhengyun 新建文章时，指定了分类

**Comment by ghost** [comment]
@tangkunyin 这是我的博客地址ruizhengyun.cn，文章分类注明了，可是点击比如“前端”就到“归档”页面了，求解（QQ:840690384）

**Comment by tangkunyin** [comment]
@ruizhengyun 你参考下文档和我站点备份的配置。应该是你配置的不对
