### ISSUE TITLE
左侧菜单栏为什么tags点击是空页面呢？？

### ISSUE THREAD

**Issue by gitHber** [tangkunyin/hexo-theme-jsimple#27]
没有生成index.html

**Comment by tangkunyin** [comment]
@gitHber 请参考我博客有一篇文章介绍主题的使用。另外站点备份的配置也看看。你配置的不对

**Comment by gitHber** [comment]
我的确是按照上面的进行的配置，可是并没有生成tags/inde.html

**Comment by ngp320** [comment]
我刚刚找到的解决方案

1. 先在 ***\hexo 下 打开 cmd , 输入 hexo new page "tags" 回车
2. 在  ***\hexo\source\tags\index.md 中添加一句  layout: "tags" 
再运行，就可以了。 
第一次添加评论，如有什么不合适的地方，希望谅解

**Comment by tangkunyin** [comment]
@ngp320 不错！

**Comment by dosedo** [comment]
> 我刚刚找到的解决方案
> 
> 1. 先在 ***\hexo 下 打开 cmd , 输入 hexo new page "tags" 回车
> 2. 在  ***\hexo\source\tags\index.md 中添加一句  layout: "tags"
>    再运行，就可以了。
>    第一次添加评论，如有什么不合适的地方，希望谅解

**### 时光费事，意境2024了。您还帮我到了我，感谢！👌🏻**
