### ISSUE TITLE
搜索框是假的？？？

### ISSUE THREAD

**Issue by 2585479524** [tangkunyin/hexo-theme-jsimple#28]
请问这个搜索框咋不能用啊啊啊？？？？求解答

**Comment by tangkunyin** [comment]
贴个图看看，可以用啊！

**Comment by 2585479524** [comment]
![j70c 5zm7hn337hqvi3q6ri](https://user-images.githubusercontent.com/32926760/39669570-0534f47e-5122-11e8-937a-b7fa5699168d.png)

也没有确定，回车也不管用，hhhhh

**Comment by tangkunyin** [comment]
@2585479524 你建好博客只有，需要把内容生成为db.json。根据这个插件来的`hexo-generator-json-content`，你研究下
