### ISSUE TITLE
中间列表不显示

### ISSUE THREAD

**Issue by BestKind** [tangkunyin/hexo-theme-jsimple#3]
你好：
       首先感谢你的主体，我很喜欢这个主体，但是我在用的时候发现我弄不出来中间的那部分的列表，烦请指点一二，谢谢！本人对于这部分比较小白！

**Comment by manwuyu** [comment]
中间那部分是  文章的标题

**Comment by tangkunyin** [comment]
楼上说的对，再有不明白了，进鹅群
