### ISSUE TITLE
Theme fails to load

### ISSUE THREAD

**Issue by johnholliday** [tangkunyin/hexo-theme-jsimple#30]
After following instructions, the site no longer loads.   Browser just hangs on the home page. Tried several browsers.

**Comment by tangkunyin** [comment]
@johnholliday Please refer to the demo：  https://github.com/shuoit/blog

**Comment by johnholliday** [comment]
Yes, I viewed the demo before applying the theme.  Once the theme was applied, the local hexo site stopped working.  If I change to another theme, it works.  Change back to jsimple, and it fails again.

**Comment by tangkunyin** [comment]
Can you show the problem snapshot image there for me?

**Comment by Screw1024** [comment]
Error ******* Please set categories in your scaffold file at least  *******
Error ******* Please set categories in your scaffold file at least  *******
ERROR F:\blog\test\themes\jsimple\layout\layout.ejs:50
    48|             // donateImg: '/images/donate-qr.png',
    49|             localSearch: {
 >> 50|                 dbPath: '/<%= config.search.path %>',
    51|                 trigger: '<%= theme.local_search.trigger %>',
    52|                 topN: '<%= theme.local_search.top_n_per_article %>',
    53|                 unescape: '<%= theme.local_search.unescape %>'

Cannot read property 'path' of undefined
作者您好，您的主题代码好像没有image的文件夹，导致报错，主题无法使用。是layout.ejs文件中的js代码段好像有点问题，请问怎么解决

**Comment by tangkunyin** [comment]
@Screw1024 我回复你邮件了。目前可以手动把develop分支的对应代码拷贝过来用。下一版修复...
