### ISSUE TITLE
手机端问题

### ISSUE THREAD

**Issue by Fengtianhe** [tangkunyin/hexo-theme-jsimple#31]
1.用手机打开，分类过多换行bug
![1151546855453_ pic](https://user-images.githubusercontent.com/15321902/50762034-d5a8ee80-12a6-11e9-884e-58e6fafda239.jpg)

2.搜索框太宽看不见
![1141546855452_ pic](https://user-images.githubusercontent.com/15321902/50762042-db9ecf80-12a6-11e9-887b-fcc38259028c.jpg)

**Comment by tangkunyin** [comment]
嗯，手机端问题确实不少。短期内不准备适配了🤣。谁有功夫，解决下吧...
