### ISSUE TITLE
markdown 的 code 模块会多出和代码行数一样的空行

### ISSUE THREAD

**Issue by lijiarui** [tangkunyin/hexo-theme-jsimple#32]
你好，很喜欢你的主题，但是更新了新版之后，发现markdown中的code 模块会出现问题。

## 预期效果
输入一段代码片段后能正常显示

## 实际效果：

markdown 中的代码：

```shell
npm install wechaty
npm install wechaty-puppet-padchat
```

博客中的样式：
![image](https://user-images.githubusercontent.com/6419514/51999536-d8df6680-246f-11e9-9be3-ef5b32cac5a2.png)

更多细节请看我的博客和项目：

复现代码：https://github.com/lijiarui/lijiarui.github.io/commit/8f812bcf2552ee121ae064870760cd270611bc57#diff-2fdbe3bd6296b768fc242d131157a96aR49

异常博客显示：
https://lijiarui.github.io/project/2018-5-1-wechaty-puppet-padchat.html

**Comment by tangkunyin** [comment]
@lijiarui 嗯。感谢反馈，看了下是这样的！

最直接粗暴的方式，关掉站点的`line_number`设定，即：
![image](https://user-images.githubusercontent.com/4197468/52029632-fcc5a980-254e-11e9-9293-016d0ab300c9.png)

之于为什么这个设定会导致排版问题，容我节后再看看......祝新年快乐

**Comment by lijiarui** [comment]
好的，多谢！

新年快乐 :)

但是我发现我原来就是false:

![image](https://user-images.githubusercontent.com/6419514/52031126-d4e33100-24cf-11e9-98a0-cb45bd6d3677.png)

以下是我的_config.yml 地址：https://github.com/lijiarui/hexo-theme-jsimple/blob/5dfe242b01856bf911d70f156737476aab91bffb/_config.yml#L45

**Comment by tangkunyin** [comment]
@lijiarui 你改错地方啦，是这里：
![image](https://user-images.githubusercontent.com/4197468/52032179-ec1b3080-255a-11e9-835a-d115d9147e47.png)

站点配置文件的_config.yml，参考下我的：[https://github.com/shuoit/blog/blob/master/_config.yml](url)

**Comment by tangkunyin** [comment]
Hexo在render html时，一般不会读theme的配置 😅

**Comment by lijiarui** [comment]
好的，多谢，确实好了 :)

**Comment by tangkunyin** [comment]
@lijiarui line-number开启导致样式错误的问题修复了。

**Comment by lijiarui** [comment]
多谢：）
