### ISSUE TITLE
add livere comment please

### ISSUE THREAD

**Issue by troycizion123** [tangkunyin/hexo-theme-jsimple#35]
hello
thank you for this wonderful theme.
would u like to consider to install the livere comment in your theme?
since we use livere a lot in asia, especially in korea and china.
thanks

**Comment by tangkunyin** [comment]
@troycizion123 You can set and use `gitment` which have been supported already.

**Comment by longqzh** [comment]
@troycizion123 , Hi, is LiveRe blocked in China? 
maybe I can add its support when I have free time ^^

**Comment by troycizion123** [comment]
@longqzh hi, 
i dont think its blocked.
cos many Chinese use it in china now.
