### ISSUE TITLE
请问怎么给文章添加目录呢？

### ISSUE THREAD

**Issue by RuiTan** [tangkunyin/hexo-theme-jsimple#38]
`对于长文章来说没有目录可太难受了呀！`

**Comment by tangkunyin** [comment]
@RuiTan 主题本身没有对TOC目录进行支持！如果确实需要目录，有两个办法：
1，使用[Next](https://github.com/theme-next/hexo-theme-next)主题；
2，提炼文章精华，即：少写一点；

**Comment by longqzh** [comment]
@tangkunyin 
 Hi～ 有计划参照next，为我们也加一个TOC目录吗？

**Comment by tangkunyin** [comment]
@longqzh 并不准备加这种东西，几个原因：
- 目前版面设计良好，增加TOC影响整体视值；
- 个人博客是否需要TOC？可能是个伪需求。如果确实有类似文档输出，可以考虑`GitBook`类似的产品；
- 尽量优化文本，多用`##`或`###`其实也能达到一定程度上的目录
