### ISSUE TITLE
Suggestion about guide

### ISSUE THREAD

**Issue by longqzh** [tangkunyin/hexo-theme-jsimple#39]
I have a suggestion about guide of Installation.

In the README.md, you guide people to 'git clone' the JSimple code to theme folder.
It works, but the problem is   
 -  when I git push my blog's source code to github, the JSimple folder in github will be empty. That means I can't backup my settings of theme to github.   
- Also If I git clone my blog's source code from github to a new PC, the JSimple folder will keep empty, and I can't generate it to html.  

So my suggestion is in the README.md telling user to `git submodule add` to instead of `git clone`, let me know if you have better idea.

**Comment by tangkunyin** [comment]
@longqzh Thanks for your suggestion.
As as workaround, you can try this plugin **[hexo-git-backup](https://github.com/coneycode/hexo-git-backup)**

**Comment by longqzh** [comment]
@tangkunyin,
Thanks your suggestion. 

I checked the git-backup you said, it just delete the .git in theme folder when it sync. So how do you git pull the upstream's update or git push to upstream without .git?

**Comment by tangkunyin** [comment]
@longqzh You can move the `.git/` and `.gitignore` to another folder when you prepare to backup with `git-back` plugin.

When you want to update theme, just move what you moved before and `git pull --rebase` again....

**Comment by longqzh** [comment]
@tangkunyin , Thanks very much for your support!
