### ISSUE TITLE
代码引用出现样式问题

### ISSUE THREAD

**Issue by Fengtianhe** [tangkunyin/hexo-theme-jsimple#40]
![image](https://user-images.githubusercontent.com/15321902/54429290-0b60cc80-475b-11e9-9f9d-31028fe443fa.png)

**Comment by Fengtianhe** [comment]
在td.gutter上加float 或者 给外层的 tr 加上display:flex都可以解决问题

**Comment by tangkunyin** [comment]
@Fengtianhe `0.0.8`版本已经解决了。试试看，参考：https://github.com/tangkunyin/hexo-theme-jsimple/issues/32

**Comment by Fengtianhe** [comment]
可以了，希望下次打tag的时候能在release中加上更新日志，又新特性能一眼就看到

**Comment by tangkunyin** [comment]
@Fengtianhe https://github.com/tangkunyin/hexo-theme-jsimple/blob/master/CHANGELOG.md
