### ISSUE TITLE
部分标签失效

### ISSUE THREAD

**Issue by yangpiena** [tangkunyin/hexo-theme-jsimple#45]
标签菜单中点击显示与之相关的文章功能，在本地hexo服务下正常，但发布到github就出现部分标签失效现象，我看你博客也存在部分标签404，请问能否解决下？

**Comment by mirindalover** [comment]
请问您标签是怎么写的呀：
我的操作
1. 根目录 _config.yml添加tag_map
2. _posts中文章.md中添加tags:
还需要别的地方吗?应该是我没有在pulbic/tags中生成index.html
使用hexo new page tags好像不适合这个主题
请指教@yangpiena

**Comment by tangkunyin** [comment]
@yangpiena 嗯，我有空看看。多谢反馈哈~

**Comment by tangkunyin** [comment]
![image](https://user-images.githubusercontent.com/4197468/60384992-c9b02380-9ab6-11e9-8503-e26561027a75.png)

@yangpiena 主题本身没问题。404的根本原因在于`GitPages`服务器对url大小写敏感导致。两种解法：
1. 将自己标签配置统一替换成小写即可（文章中需要于此对应，区分大小写）；
2. 让官方对url大小写不敏感；

注意：`public/tags`下生成的目录名和文章中定义的标签名一致。如果`_config.yml`中别名于文章的不一样，则依然会404...

**Comment by yangpiena** [comment]
![image](https://user-images.githubusercontent.com/19336724/60498569-71149c80-9ce9-11e9-9129-67b9db449361.png)
谢谢你的帮助，我试了将大写换成小写，有些标签正常了，但有些仍然为空，让人不知所云。

**Comment by tangkunyin** [comment]
@yangpiena 你把gitpages上的public/tags文件夹全部删掉，再重新把本地的push上去，应该就好了（即便本地变成小写了，服务器的大写文件夹在push时貌似并不会被覆盖）。

**Comment by yangpiena** [comment]
非常感谢，问题已解决。
