### ISSUE TITLE
请问为什么人文或者科技分类栏一直404

### ISSUE THREAD

**Issue by tsxce** [tangkunyin/hexo-theme-jsimple#49]
您好，我在post的md里面是这么写的，本人对hexo是个小白。谢谢！
categories: 技术
tags:
    - hexo
    - webx
keywords:
description:

**Comment by tangkunyin** [comment]
@xiechen0692 看下主题使用说明以及这篇文章：https://shuoit.net/tech/jsimple-usage-1492480198.html

**Comment by 0xSunsetJe3us** [comment]
> @xiechen0692 看下主题使用说明以及这篇文章：https://shuoit.net/tech/jsimple-usage-1492480198.html

Thanks!
