### ISSUE TITLE
Issue about Cover image path

### ISSUE THREAD

**Issue by longqzh** [tangkunyin/hexo-theme-jsimple#52]
The cover image's path is hard coded in  `js/SimpleCore.js` (changeReadModel). 

When `root` value is NOT "/" in site's `_config.yml`, the cover image path will be broken.

For instance,
in site's `config.yml`,  
```
url : http://site/sub
root:/sub/
```

the cover image path would ignore the `sub`, and be `http://site/images/cover-night.jpg`

---

Let me know if you can fix the bug:)

**Comment by tangkunyin** [comment]
@longqzh Sorry and thanks for this report, I will check it as soon as possible

**Comment by tangkunyin** [comment]
@longqzh Bug has been fixed in version 0.0.9.
