### ISSUE TITLE
在哪里可以设置首页大图

### ISSUE THREAD

**Issue by makoMakoGo** [tangkunyin/hexo-theme-jsimple#56]
我的左侧显示不出来图片~ 在——config.yml中也没发现配置项，在本地f12后 `background: url(https://removeif.github.io/images/cover-day.jpg) center center / cover no-repeat;` 我都没设置~~这应该去哪里改呢

**Comment by tangkunyin** [comment]
@zhu-jl18 直接覆盖主题资源文件就行啦！

```
xxx/source/images/cover-day.jpg | cover-night.jpg
```
