### ISSUE TITLE
我的项目应用该主题提示：Cannot read property 'name' of undefined、

### ISSUE THREAD

**Issue by wangpengliang815** [tangkunyin/hexo-theme-jsimple#7]
![image](https://cloud.githubusercontent.com/assets/13447881/24031544/23876600-0b1e-11e7-8fb2-aed521764c1f.png)
  
不理解这是什么意思，如果您有时间请回复一下，谢谢。

**Comment by tangkunyin** [comment]
@GnailGnepGnaw https://github.com/tangkunyin/hexo-theme-jsimple/issues/6
这个或许能帮助你
