### ISSUE TITLE
分类如何设置，标签不显示呢

### ISSUE THREAD

**Issue by wangpengliang815** [tangkunyin/hexo-theme-jsimple#8]
感谢您之前的解释，我现在已经可以成功使用您的主题，但是我现在的标签分类显示不了

![image](https://cloud.githubusercontent.com/assets/13447881/24106822/153164ea-0dc4-11e7-8fdf-8b2582bdc5ec.png)

我没有很理解您这里的意思，如果方便的话，希望您能再次指导一下，不胜感激。

**Comment by tangkunyin** [comment]
@GnailGnepGnaw 你好，这是需要文章模板里也配置，比如`scaffolds`文件中的`post.md`
```
title: {{ title }}
date: {{ date }}
categories: 技术
tags: 
keywords: 
description: 
author: 唐先森
photos: 
---
```

**Comment by tangkunyin** [comment]
接二楼：如上的模板配置后，每次新建的文章里都会有分类和标签字段，写文章时把他们填上就好了。
如果需要改造主题增加信息，也是在这里设置变量的。有问题接着问，看到第一时间回复！
